// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mFc4yAqKc8BNb8skLTrskMqbBdt61XU',
    appId: '1:323936906674:web:e3a83315470963458f88ab',
    messagingSenderId: '323936906674',
    projectId: 'payment-9f13a',
    authDomain: 'payment-9f13a.firebaseapp.com',
    storageBucket: 'payment-9f13a.firebasestorage.app',
    measurementId: 'G-T95EHYEN7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2pK4RXQrTbJSNL6P_yVUMT4u8qkxpyAQ',
    appId: '1:323936906674:android:3d45a6f92834e3098f88ab',
    messagingSenderId: '323936906674',
    projectId: 'payment-9f13a',
    storageBucket: 'payment-9f13a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-703b4hnU7cQcl9sONFrlKQST4Vkey5U',
    appId: '1:323936906674:ios:62f3b324cf6584bf8f88ab',
    messagingSenderId: '323936906674',
    projectId: 'payment-9f13a',
    storageBucket: 'payment-9f13a.firebasestorage.app',
    iosBundleId: 'com.example.Payment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-703b4hnU7cQcl9sONFrlKQST4Vkey5U',
    appId: '1:323936906674:ios:62f3b324cf6584bf8f88ab',
    messagingSenderId: '323936906674',
    projectId: 'payment-9f13a',
    storageBucket: 'payment-9f13a.firebasestorage.app',
    iosBundleId: 'com.example.Payment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1mFc4yAqKc8BNb8skLTrskMqbBdt61XU',
    appId: '1:323936906674:web:6083264ae42f61ed8f88ab',
    messagingSenderId: '323936906674',
    projectId: 'payment-9f13a',
    authDomain: 'payment-9f13a.firebaseapp.com',
    storageBucket: 'payment-9f13a.firebasestorage.app',
    measurementId: 'G-ZQ96X4G8CP',
  );
}
