name: Android Fastlane Firebase Distribution

on:
  push:
    branches:
      - ui_for_app

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create directory for api_keys
        run: mkdir -p lib/Utilities

      - name: Inject api_keys.dart
        run: |
          cat <<EOF > lib/Utilities/api_keys.dart
          ${{ secrets.API_KEYS_FILE }}
          EOF

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.7"
          bundler-cache: true
          working-directory: android

      - name: Distribute to Firebase via Fastlane
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          bundle exec fastlane android firebase_release
        working-directory: android
